Repository static-web-server/static-web-server, pull requests merged in 2022-11, with the labels that each got.

#158 docs: Minor fixes regarding environment variables
  docs/content/configuration/environment-variables.md
Labels: documentation, v2

#160 HTTP-related extension traits
  src/compression.rs
  src/directory_listing.rs
  src/error_page.rs
  src/exts/http.rs
  src/exts/mod.rs
  src/handler.rs
  src/lib.rs
  src/static_files.rs
Labels: enhancement, codebase

#161 Fix missing `SERVER` prefix for the `redirect-trailing-slash` feature flag
  docs/content/configuration/command-line-arguments.md
  docs/content/configuration/environment-variables.md
  src/settings/cli.rs
Labels: v2, bugfix

#162 Ignore Unix hidden files/directories (dotfiles)
  docs/content/configuration/command-line-arguments.md
  docs/content/configuration/config-file.md
  docs/content/configuration/environment-variables.md
  docs/content/features/directory-listing.md
  docs/content/features/ignore-files.md
  docs/mkdocs.yml
  src/directory_listing.rs
  src/exts/mod.rs
  src/exts/path.rs
  src/handler.rs
  src/server.rs
  src/settings/cli.rs
  src/settings/file.rs
  src/settings/mod.rs
  src/static_files.rs
  tests/compression_static.rs
  tests/dir_listing.rs
  tests/fixtures/public/.dotfile
  tests/static_files.rs
Labels: enhancement, v2
