Repository static-web-server/static-web-server, pull requests merged in 2022-09, with the labels that each got.

#137 Relative paths for directory listing entries
  docs/content/features/directory-listing.md
  src/static_files.rs
  tests/dir_listing.rs
Labels: enhancement, v2

#138 Add logging of real remote IP - in case of proxies
  docs/content/features/logging.md
  src/handler.rs
Labels: enhancement, v2

#140 Fix typos
  CHANGELOG.md
  docker/alpine/entrypoint.sh
  docs/content/configuration/config-file.md
  docs/content/features/logging.md
  src/redirects.rs
  src/rewrites.rs
  src/settings/file.rs
  tests/toml/config.toml
Labels: documentation, enhancement, v2

#141 Add typos job to GitHub CI devel workflow
  .github/workflows/config/typos.toml
  .github/workflows/devel.yml
Labels: enhancement, v2, ci

#139 Support for serving pre-compressed files
  .github/workflows/devel.yml
  .gitignore
  src/compression.rs
  src/compression_static.rs
  src/directory_listing.rs
  src/handler.rs
  src/lib.rs
  src/server.rs
  src/settings/cli.rs
  src/settings/file.rs
  src/settings/mod.rs
  src/static_files.rs
  tests/compression_static.rs
  tests/dir_listing.rs
  tests/fixtures/public/index.html.gz
  tests/static_files.rs
  tests/toml/config.toml
Labels: enhancement, v2
