Repository static-web-server/static-web-server, pull requests merged in 2022-10, with the labels that each got.

#144 CORS expose headers option
  docs/content/configuration/command-line-arguments.md
  docs/content/configuration/environment-variables.md
  docs/content/features/cors.md
  docs/man/static-web-server.1.rst
  src/cors.rs
  src/server.rs
  src/settings/cli.rs
  src/settings/file.rs
  src/settings/mod.rs
  tests/cors.rs
Labels: enhancement, v2

#150 Properly encoding of directory listing links
  src/directory_listing.rs
  tests/dir_listing.rs
  tests/fixtures/public/spécial directöry/spécial file.txt~
Labels: v2, bugfix

#151 Directory listing format
  .github/workflows/devel.yml
  Cargo.lock
  Cargo.toml
  src/directory_listing.rs
  src/handler.rs
  src/server.rs
  src/settings/cli.rs
  src/settings/file.rs
  src/settings/mod.rs
  src/static_files.rs
  tests/compression_static.rs
  tests/dir_listing.rs
  tests/static_files.rs
  tests/toml/config.toml
Labels: enhancement, v2

#153 Make static file reading (content/metadata) operations sync
  src/compression_static.rs
  src/static_files.rs
  tests/static_files.rs
Labels: enhancement, v2, performance

#155 SWS benchmarks with several web servers
  .gitignore
  Makefile
  README.md
  benchmark/BENCHMARKS.md
  benchmark/sws_benchmarks.csv
  benchmark/sws_benchmarks.png
  benchmark/wrk_collector.lua
Labels: v2, benchmarks

#157 Clarify benchmark context and remarks
  benchmark/BENCHMARKS.md
  benchmark/sws_benchmarks.png
Labels: documentation, enhancement, v2, benchmarks
