Repository static-web-server/static-web-server, pull requests merged in 2023-03, with the labels that each got.

#183 Add optional support for http2
  Cargo.toml
  src/lib.rs
  src/server.rs
  src/settings/cli.rs
  src/settings/file.rs
  src/settings/mod.rs
Labels: enhancement, v2

#180 Add support for .html prefixing when the path doesn't exist
  src/static_files.rs
Labels: enhancement, v2

#185 Make signals optional for non-unix or non-windows systems
  src/lib.rs
  src/logger.rs
  src/server.rs
Labels: enhancement, v2

#186 Check missing auto index for directory requests when `compression-static` is enabled
  src/compression_static.rs
  src/static_files.rs
Labels: v2, bugfix

#181 Add support for max_blocking_threads
  docs/content/configuration/command-line-arguments.md
  docs/content/configuration/environment-variables.md
  src/server.rs
  src/settings/cli.rs
  src/settings/file.rs
  src/settings/mod.rs
Labels: enhancement, v2

#189 ci: workflow for publishing to crates.io
  .github/workflows/release.crate.yml
Labels: enhancement, v2, ci, library

#190 `static_web_server` crate
  .github/workflows/release.crate.yml
  Cargo.toml
  Makefile
  src/basic_auth.rs
  src/compression.rs
  src/compression_static.rs
  src/control_headers.rs
  src/cors.rs
  src/custom_headers.rs
  src/directory_listing.rs
  src/error.rs
  src/error_page.rs
  src/exts/http.rs
  src/exts/path.rs
  src/fallback_page.rs
  src/handler.rs
  src/helpers.rs
  src/lib.rs
  src/logger.rs
  src/redirects.rs
  src/rewrites.rs
  src/security_headers.rs
  src/server.rs
  src/service.rs
  src/settings/cli.rs
  src/settings/file.rs
  src/settings/mod.rs
  src/signals.rs
  src/static_files.rs
  src/tls.rs
  src/transport.rs
  src/winservice.rs
Labels: enhancement, v2, library
