Repository static-web-server/static-web-server, pull requests merged in 2023-04, with the labels that each got.

#192 Improve error handling on directory listing when read directory entries
  src/directory_listing.rs
Labels: enhancement, v2

#194 Android ARM64 target support
  .github/workflows/devel.yml
  .github/workflows/release.docker.yml
  .github/workflows/release.yml
  ci/cargo.sh
  ci/install-tools.sh
Labels: enhancement, v2, target

#197 `zstd` auto-compression support
  Cargo.lock
  Cargo.toml
  src/compression.rs
  src/compression_static.rs
Labels: enhancement, v2

#199 Update alpine to 3.17.3
  docker/alpine/Dockerfile
  docker/devel/Dockerfile.alpine
Labels: enhancement, dependency, docker
