Repository static-web-server/static-web-server, pull requests merged in 2023-07, with the labels that each got.

#235 Replacements support for URL Rewrites destination
  Cargo.lock
  Cargo.toml
  docs/content/features/url-rewrites.md
  src/handler.rs
  src/settings/mod.rs
  tests/toml/config.toml
Labels: enhancement, v2, advanced-feature

#238 Add an optional and quiet /health endpoint
  docs/content/configuration/environment-variables.md
  docs/content/features/health-endpoint.md
  docs/mkdocs.yml
  src/handler.rs
  src/server.rs
  src/settings/cli.rs
  src/settings/file.rs
  src/settings/mod.rs
Labels: enhancement, v2

#239 Replacements support for URL Redirects destination
  docs/content/features/url-redirects.md
  docs/content/features/url-rewrites.md
  src/handler.rs
  src/redirects.rs
  src/settings/mod.rs
  tests/toml/config.toml
Labels: enhancement, v2, advanced-feature

#244 URL Rewrites don't work without replacements
  src/settings/mod.rs
  tests/toml/config.toml
Labels: v2, bugfix, regression
