Repository static-web-server/static-web-server, pull requests merged in 2023-11, with the labels that each got.

#281 Auto-config file detection at startup
  src/bin/server.rs
  src/server.rs
  src/settings/cli.rs
  src/settings/mod.rs
  src/winservice.rs
Labels: enhancement, v2

#282 Improve server maintenance mode logging
  docs/content/features/maintenance-mode.md
  src/maintenance_mode.rs
Labels: enhancement, v2

#283 Windows ARM64 target
  .github/workflows/devel.yml
  .github/workflows/release.yml
  docs/content/download-and-install.tmpl.md
  docs/content/platforms-architectures.md
Labels: enhancement, v2, Windows, target

#284 Load HTML error pages content at runtime
  docs/content/configuration/command-line-arguments.md
  docs/content/configuration/config-file.md
  docs/content/configuration/environment-variables.md
  src/error_page.rs
  src/handler.rs
  src/server.rs
  src/settings/cli.rs
Labels: enhancement, v2

#287 Readme: Fix typo in the Spelling of Wasmer
  README.md
Labels: documentation, enhancement

#286 Release Docker Manual CI workflow (Debian)
  .github/workflows/devel.docker.yml
  .github/workflows/devel.yml
  .github/workflows/release.docker.manual.yml
  docker/debian/Dockerfile
Labels: enhancement, docker

#290 Fix Windows ARM64 binary does not run due to some missing DLLs
  .cargo/config.toml
Labels: v2, Windows, bugfix

#291 Statically link the C runtime for Windows MSVC x86
  .cargo/config.toml
Labels: enhancement, v2, Windows

#288 Release Manual CI Workflow
  .github/workflows/release.build.manual.yml
Labels: enhancement, ci
