Repository static-web-server/static-web-server, pull requests merged in 2023-06, with the labels that each got.

#211 Migrate from structopt to clap v3
  Cargo.lock
  Cargo.toml
  src/directory_listing.rs
  src/settings/cli.rs
  src/settings/mod.rs
Labels: enhancement, v2, dependency

#215 Support for boolean flags without explicit values
  Cargo.lock
  Cargo.toml
  src/directory_listing.rs
  src/server.rs
  src/settings/cli.rs
  src/settings/mod.rs
Labels: enhancement, v2

#216 Fix security headers not enabled by default issue when using config file
  src/settings/mod.rs
Labels: v2, bugfix

#219 Fix regression when using empty values for `--page-fallback` or `SERVER_FALLBACK_PAGE`
  src/server.rs
  src/settings/cli.rs
  src/settings/mod.rs
Labels: v2, bugfix

#221 feat: `basic-auth` Cargo feature
  Cargo.toml
  docs/content/building-from-source.md
  src/handler.rs
  src/lib.rs
  src/server.rs
  src/settings/cli.rs
  src/settings/mod.rs
Labels: enhancement, v2, library

#231 Optional `redirect` for URL Rewrites feature
  docs/content/features/url-rewrites.md
  src/handler.rs
  src/rewrites.rs
  src/settings/file.rs
  src/settings/mod.rs
  tests/toml/config.toml
Labels: enhancement, v2, advanced-feature

#232 Docker images support for GitHub Container Registry
  .github/workflows/release.docker.yml
Labels: enhancement, v2, ci, docker
