Repository static-web-server/static-web-server, pull requests merged in 2024-06, with the labels that each got.

#453 Fix duplicate `Vary` response headers for `compression` and `compression-static` features
  src/compression.rs
  src/compression_static.rs
  src/handler.rs
  src/testing.rs
  tests/compression.rs
  tests/compression_static.rs
  tests/experimental_metrics.rs
  tests/handler.rs
  tests/redirects.rs
  tests/rewrites.rs
Labels: v2, bugfix

#454 Disable symlinks option
  docs/content/configuration/command-line-arguments.md
  docs/content/configuration/environment-variables.md
  docs/content/features/disable-symlinks.md
  docs/mkdocs.yml
  src/directory_listing.rs
  src/handler.rs
  src/server.rs
  src/settings/cli.rs
  src/settings/file.rs
  src/settings/mod.rs
  src/static_files.rs
  src/testing.rs
  tests/compression_static.rs
  tests/dir_listing.rs
  tests/fixtures/public/symlink
  tests/static_files.rs
Labels: enhancement, v2, general

#456 Improve typos configuration
  .github/workflows/config/typos.toml
  CHANGELOG.md
Labels: enhancement, v2, ci

#457 Remove redundant `async` function signatures
  src/compression_static.rs
  src/control_headers.rs
  src/directory_listing.rs
  src/https_redirect.rs
  src/response.rs
  src/server.rs
  src/static_files.rs
  tests/cors.rs
  tests/settings.rs
Labels: enhancement, v2, codebase
