Repository static-web-server/static-web-server, pull requests merged in 2024-09, with the labels that each got.

#328 Experimental in-memory files cache with eviction policy support
  .github/workflows/devel.yml
  Cargo.lock
  Cargo.toml
  docs/content/building-from-source.md
  src/cors.rs
  src/handler.rs
  src/lib.rs
  src/mem_cache/cache.rs
  src/mem_cache/mod.rs
  src/mem_cache/stream.rs
  src/response.rs
  src/server.rs
  src/settings/file.rs
  src/settings/mod.rs
  src/static_files.rs
  src/testing.rs
  tests/compression_static.rs
  tests/dir_listing.rs
  tests/static_files.rs
  tests/toml/config.toml
Labels: enhancement, v2, advanced-feature, experimental

#475 Support for generating man pages and completions
  Cargo.lock
  Cargo.toml
  docs/content/features/man-pages-completions.md
  docs/mkdocs.yml
  src/bin/server.rs
  src/settings/cli.rs
  src/settings/mod.rs
Labels: enhancement, v2

#478 Update Alpine (3.18.9) and Debian (12.7) Docker images
  docker/alpine/Dockerfile
  docker/debian/Dockerfile
  docker/devel/Dockerfile.alpine
  docker/devel/Dockerfile.debian
Labels: enhancement, v2, dependency, docker

#480 Fix issues when building SWS without default features
  .github/workflows/devel.yml
  docs/content/building-from-source.md
  src/headers_ext/mod.rs
  src/http_ext.rs
  src/lib.rs
  src/server.rs
  src/static_files.rs
  tests/compression.rs
  tests/compression_static.rs
  tests/handler.rs
  tests/static_files.rs
Labels: v2, bugfix, library

#479 Update dependencies 08.09.2024
  Cargo.lock
  Cargo.toml
Labels: enhancement, v2, dependency, bugfix

#482 Add in-memory files cache to the Cargo `experimental` feature list
  Cargo.toml
  src/handler.rs
  src/lib.rs
  src/response.rs
  src/server.rs
  src/settings/file.rs
  src/settings/mod.rs
  src/static_files.rs
  src/testing.rs
  tests/compression_static.rs
  tests/dir_listing.rs
  tests/static_files.rs
Labels: enhancement, v2, library, experimental
