Repository static-web-server/static-web-server, pull requests merged in 2024-12, with the labels that each got.

#504 docs: fix anchor links
  .github/workflows/devel.yml
  docs/content/features/cors.md
  docs/content/features/health-endpoint.md
  docs/content/features/logging.md
  docs/content/features/trailing-slash-redirect.md
  docs/docker-compose.yml
  docs/mkdocs.yml
Labels: documentation, enhancement, v2

#506 refactor: prevent single wildcards from matching path separators for URL Rewrites
  docs/content/features/url-redirects.md
  docs/content/features/url-rewrites.md
  src/settings/mod.rs
  tests/rewrites.rs
Labels: enhancement, v2, breaking

#511 The closing body tag has been moved right before the closing html tag
  src/directory_listing.rs
Labels: v2, bugfix

#512 Build and push `devel` Docker image on master changes via CI workflow
  .github/workflows/release.docker.devel.yml
Labels: enhancement, v2, ci
