Repository static-web-server/static-web-server, pull requests merged in 2024-11, with the labels that each got.

#490 Update dependencies 26-10-2024
  .cirrus.yml
  Cargo.lock
  Cargo.toml
  src/handler.rs
  src/lib.rs
  tests/handler.rs
Labels: enhancement, v2, dependency, bugfix

#486 Truenas deprecated
  docs/content/download-and-install.md
  docs/content/download-and-install.template.md
  docs/content/features/docker.md
Labels: documentation, v2

#495 Improve X-Forwarded-For handling
  docs/content/configuration/command-line-arguments.md
  docs/content/configuration/config-file.md
  docs/content/configuration/environment-variables.md
  docs/content/features/logging.md
  src/handler.rs
  src/log_addr.rs
  src/server.rs
  src/settings/cli.rs
  src/settings/file.rs
  src/settings/mod.rs
  src/testing.rs
Labels: enhancement, v2

#497 Add Contributing, code of conduct and code guidelines pages
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  docs/CODE_OF_CONDUCT.md
  docs/CODE_STYLE.md
  docs/COMMITS.md
  docs/PULL_REQUESTS.md
  docs/man/static-web-server.1.rst
Labels: documentation, v2

#502 Update dependencies 28.10.2024
  Cargo.lock
  Cargo.toml
  src/cors.rs
Labels: enhancement, v2, dependency, bugfix

#503 Add additional redirect tests
  tests/fixtures/toml/redirects.toml
  tests/redirects.rs
Labels: enhancement, v2, testing

#505 Update Alpine (3.19.4) and Debian (12.8) Docker images
  docker/alpine/Dockerfile
  docker/debian/Dockerfile
  docker/devel/Dockerfile.alpine
  docker/devel/Dockerfile.debian
Labels: enhancement, v2, dependency, docker
