Repository static-web-server/static-web-server, pull requests merged in 2024-05, with the labels that each got.

#381 New compression level option support
  docs/content/configuration/command-line-arguments.md
  docs/content/configuration/config-file.md
  docs/content/configuration/environment-variables.md
  docs/content/features/compression.md
  src/compression.rs
  src/handler.rs
  src/server.rs
  src/settings/cli.rs
  src/settings/file.rs
  src/settings/mod.rs
  src/testing.rs
  tests/static_files.rs
Labels: enhancement, v2

#375 Do not mention request body type unnecessarily #340
  src/basic_auth.rs
  src/compression.rs
  src/compression_static.rs
  src/control_headers.rs
  src/cors.rs
  src/custom_headers.rs
  src/fallback_page.rs
  src/health.rs
  src/https_redirect.rs
  src/maintenance_mode.rs
  src/metrics.rs
  src/redirects.rs
  src/rewrites.rs
  src/security_headers.rs
Labels: enhancement, v2, codebase

#385 Display file size for empty files as "0 B", not as "-"
  src/directory_listing.rs
Labels: v2, bugfix

#384 Drop custom conversion between SystemTime and DateTime
  src/directory_listing.rs
Labels: enhancement, v2

#388 Move remote and real IP addresses logging to its own module
  src/handler.rs
  src/health.rs
  src/lib.rs
  src/log_addr.rs
  src/server.rs
Labels: enhancement, v2, codebase

#424 Re-organize file system-related modules
  src/compression_static.rs
  src/fs/meta.rs
  src/fs/mod.rs
  src/fs/path.rs
  src/fs/stream.rs
  src/lib.rs
  src/response.rs
  src/static_files.rs
Labels: enhancement, v2, codebase

#441 Fix unexpected `cfg` condition-name `wasm` in Rust nightly
  src/settings/cli.rs
Labels: v2, bugfix, target, rust:nightly-beta

#442 Log virtual-hosts information per request
  src/handler.rs
  src/lib.rs
  src/virtual_hosts.rs
Labels: enhancement, v2, advanced-feature

#444 Show more details about the server via version flags (`-V`, `--version`)
  Cargo.lock
  Cargo.toml
  build.rs
  src/bin/server.rs
  src/settings/cli.rs
  src/settings/cli_output.rs
  src/settings/mod.rs
Labels: enhancement, v2

#439 Look for all accepted encodings for precompressed files but keeping the quality ordering
  src/compression.rs
  src/compression_static.rs
  tests/compression_static.rs
  tests/dir_listing.rs
  tests/fixtures/public/404.html.br
Labels: enhancement, v2

#446 Fix jemalloc unsupported system page size in Linux ARM64 musl
  .github/workflows/release.yml
  Cargo.toml
Labels: v2, bugfix, target, docker, linux

#447 Re-enable Windows 7 builds support previously dropped in v2.31.0
  .github/workflows/devel.yml
  .github/workflows/release.yml
Labels: enhancement, v2, Windows, target

#449 update installer.sh to support overriding default variables
  docs/content/download-and-install.md
  scripts/installer.sh
Labels: enhancement, v2, installer, linux, unix

#450 Improve `Download and Install` documetation page
  docs/content/assets/style.css
  docs/content/download-and-install.generated.md
  docs/content/download-and-install.md
  docs/content/download-and-install.tmpl.md
  docs/mkdocs.yml
  scripts/ci/post_release_updates.sh
Labels: documentation, v2, codebase

#452 Fix incorrect `Content-Encoding` for pre-compressed Zstd file requests
  src/compression_static.rs
  src/fs/meta.rs
  src/static_files.rs
  tests/compression_static.rs
  tests/dir_listing.rs
  tests/fixtures/public/main.js.zst
Labels: v2, bugfix
