Repository static-web-server/static-web-server, pull requests merged in 2024-04, with the labels that each got.

#334 Minor performance improvements when serving static files
  benches/Cargo.toml
  benches/http_ext.rs
  src/compression.rs
  src/control_headers.rs
  src/file_path.rs
  src/http_ext.rs
  src/signals.rs
Labels: enhancement, v2, performance

#333 Fix missing custom headers for directory requests (trailing slash)
  src/custom_headers.rs
  src/handler.rs
  src/static_files.rs
  tests/compression_static.rs
  tests/dir_listing.rs
  tests/fixtures/toml/handler.toml
  tests/handler.rs
  tests/static_files.rs
Labels: v2, advanced-feature, bugfix

#337 Reduce some allocations in several modules
  src/custom_headers.rs
  src/error_page.rs
  src/maintenance_mode.rs
  src/redirects.rs
  src/rewrites.rs
  src/settings/mod.rs
Labels: enhancement, v2, performance

#339 Fix build error when using specific or no Cargo compression features
  src/compression.rs
  src/compression_static.rs
  src/handler.rs
  src/lib.rs
  src/server.rs
  src/settings/cli.rs
  src/settings/file.rs
  src/settings/mod.rs
  src/static_files.rs
  src/testing.rs
  tests/compression_static.rs
  tests/static_files.rs
Labels: v2, bugfix, library

#344 Move health endpoint-related code into a separate file
  src/handler.rs
  src/health.rs
  src/lib.rs
  src/server.rs
Labels: enhancement, v2, codebase

#343 Fix CORS does not work when used with Basic Auth
  docs/content/features/cors.md
  src/cors.rs
  src/handler.rs
  src/settings/cli.rs
Labels: v2, bugfix

#346 Move all of Basic authentication logic into basic_auth module
  src/basic_auth.rs
  src/cors.rs
  src/handler.rs
  src/server.rs
Labels: enhancement, v2, codebase

#348 Move all redirect handling logic into the redirects module
  src/handler.rs
  src/redirects.rs
  src/settings/mod.rs
Labels: enhancement, v2, codebase

#349 Move most of CORS-related code into the cors module
  src/cors.rs
  src/handler.rs
  src/server.rs
Labels: enhancement, v2, codebase

#350 Move most of maintenance mode logic into maintenance_mode module
  src/handler.rs
  src/maintenance_mode.rs
  src/server.rs
Labels: enhancement, v2, codebase

#351 Move various code related to header handling to the respective modules
  src/control_headers.rs
  src/custom_headers.rs
  src/handler.rs
  src/security_headers.rs
  src/server.rs
Labels: enhancement, v2, codebase

#354 Replaced fork of the headers module by an in-tree handler for the Accept-Encoding header
  Cargo.lock
  Cargo.toml
  src/compression.rs
  src/compression_static.rs
  src/headers_ext/accept_encoding.rs
  src/headers_ext/content_coding.rs
  src/headers_ext/mod.rs
  src/headers_ext/quality_value.rs
  src/lib.rs
Labels: enhancement, v2, dependency, codebase

#353 Move all rewrite handling logic into the rewrites module
  docs/content/features/url-rewrites.md
  src/handler.rs
  src/redirects.rs
  src/rewrites.rs
Labels: enhancement, v2, codebase

#355 Run load testing benchmarks comparison for each commit via Github Actions
  .github/workflows/perfcheck.yml
  scripts/ci/vegeta_report_to_csv.jq
Labels: enhancement, v2, performance, ci, benchmarks

#357 Improve performance of directory listings
  src/directory_listing.rs
Labels: enhancement, v2, performance

#361 Fix Accept-Encoding handling to work correctly if only two compression schemes are available
  src/compression.rs
  src/headers_ext/accept_encoding.rs
  tests/static_files.rs
Labels: v2, bugfix, library

#360 Improve recognition of text MIME types for compression
  Cargo.lock
  Cargo.toml
  src/compression.rs
Labels: enhancement, v2

#368 Fix errors due to "unused code" when features are disabled
  src/handler.rs
  src/lib.rs
Labels: v2, bugfix, codebase

#369 Move all compression-related code into compression and compression_static modules
  src/compression.rs
  src/compression_static.rs
  src/handler.rs
  src/server.rs
  src/static_files.rs
Labels: enhancement, v2, codebase

#367 Use maud templates and serde_json for directory listings
  Cargo.lock
  Cargo.toml
  src/directory_listing.rs
Labels: enhancement, v2, dependency

#371 Don't percent-encode unreserved characters for directory listing links
  src/directory_listing.rs
  tests/dir_listing.rs
  tests/fixtures/public/spécial-directöry.net/spécial file.txt~
Labels: enhancement, v2, bugfix

#372 Move all fallback page logic into the corresponding module
  src/compression_static.rs
  src/control_headers.rs
  src/cors.rs
  src/custom_headers.rs
  src/fallback_page.rs
  src/handler.rs
  src/security_headers.rs
  src/server.rs
Labels: enhancement, v2, codebase

#373 Move directory listing initialization into the corresponding module
  src/directory_listing.rs
  src/server.rs
Labels: enhancement, v2, codebase

#374 Make sure to deal with malformed UTF-8 in file names
  src/directory_listing.rs
  src/file_path.rs
Labels: v2, bugfix

#376 Fix the display format for file sizes
  Cargo.lock
  Cargo.toml
  src/directory_listing.rs
Labels: v2, bugfix

#379 Add caddy to performance benchmarks
  .github/workflows/perfcheck.yml
Labels: enhancement, v2, ci, benchmarks

#382 Fixed clippy warning
  src/directory_listing.rs
Labels: v2, bugfix, codebase

#383 Fixed compile errors if only deflate compression is enabled
  src/compression_static.rs
Labels: v2, bugfix
