Repository static-web-server/static-web-server, pull requests merged in 2025-05, with the labels that each got.

#542 Fix generic server `INFO` log output entries at startup, even on higher log levels
  src/basic_auth.rs
  src/bin/server.rs
  src/compression.rs
  src/compression_static.rs
  src/control_headers.rs
  src/cors.rs
  src/directory_listing.rs
  src/fallback_page.rs
  src/health.rs
  src/log_addr.rs
  src/logger.rs
  src/maintenance_mode.rs
  src/mem_cache/cache.rs
  src/metrics.rs
  src/security_headers.rs
  src/server.rs
  src/settings/mod.rs
Labels: v2, bugfix

#543 Control log ANSI output via boolean `--log-with-ansi` option
  docs/content/configuration/environment-variables.md
  docs/content/features/logging.md
  src/logger.rs
  src/settings/cli.rs
  src/settings/file.rs
  src/settings/mod.rs
Labels: enhancement, v2

#545 Update dependencies 26.05.2025 and MSRV 1.81.0
  .cargo/audit.toml
  .github/workflows/devel.yml
  .github/workflows/release.yml
  Cargo.lock
  Cargo.toml
  build.rs
  docs/content/building-from-source.md
  tests/experimental_metrics.rs
Labels: v2, dependency, breaking

#544 Add support for downloading a directory as a compressed tarball
  Cargo.lock
  Cargo.toml
  docs/content/configuration/command-line-arguments.md
  docs/content/configuration/config-file.md
  docs/content/configuration/environment-variables.md
  docs/content/features/directory-listing.md
  src/directory_listing.rs
  src/directory_listing_download.rs
  src/handler.rs
  src/lib.rs
  src/server.rs
  src/settings/cli.rs
  src/settings/file.rs
  src/settings/mod.rs
  src/static_files.rs
  src/testing.rs
  tests/dir_listing.rs
  tests/dir_listing_download.rs
  tests/static_files.rs
Labels: enhancement, v2

#546 Update dependencies 30.05.2025 and MSRV to 1.82.0
  .cirrus.yml
  .github/workflows/devel.yml
  Cargo.lock
  Cargo.toml
  docs/content/building-from-source.md
  tests/dir_listing_download.rs
Labels: enhancement, v2, security, dependency
