Repository static-web-server/static-web-server, pull requests merged in 2025-02, with the labels that each got.

#521 Optionally log X-Real-IP header.
  docs/content/configuration/command-line-arguments.md
  docs/content/configuration/environment-variables.md
  docs/content/features/logging.md
  src/handler.rs
  src/log_addr.rs
  src/server.rs
  src/settings/cli.rs
  src/settings/file.rs
  src/settings/mod.rs
  src/testing.rs
Labels: enhancement, v2

#522 Improve fallback page path checking and logging
  docs/content/configuration/command-line-arguments.md
  docs/content/configuration/environment-variables.md
  docs/content/features/error-pages.md
  src/fallback_page.rs
  src/settings/cli.rs
Labels: enhancement, v2

#523 Add missing query string to the URI trailing slash redirect
  src/static_files.rs
Labels: bug, v2

#524 Update dependencies 06-02-2025
  Cargo.lock
  Cargo.toml
Labels: enhancement, v2, dependency, bugfix

#525 Improve post release updates CI workflow
  .github/workflows/release.updates.yml
  docs/content/download-and-install.template.md
  scripts/ci/post_release_updates.sh
Labels: enhancement, v2, ci
